In [15]:
import pandas as pd 
import numpy as np
s = pd.Series([1,2,3,4,5] )
print(s)
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
3

In [16]:
s1 = pd.Series([10,20,30,40,50], index = ["Om","Rahul","Banty","Nisha","Sahil"])
print(s1)
print(s1["Om"])
print(s1.index)
print(s1.dtype)
print(np.sum(s1))

Om       10
Rahul    20
Banty    30
Nisha    40
Sahil    50
dtype: int64
10
Index(['Om', 'Rahul', 'Banty', 'Nisha', 'Sahil'], dtype='object')
int64
150

In [30]:
# Dataframe

info = {
    "name" : ["Nisha","Rushikesh","Rahul","Banty"],
    "Age" : [18,20,21,25],
    "CGP" : [7.5,9.6,8.5,9]
}
df = pd.DataFrame(info)
print(info)
print(df)
print(df.index)
print(df.columns)

{'name': ['Nisha', 'Rushikesh', 'Rahul', 'Banty'], 'Age': [18, 20, 21, 25], 'CGP': [7.5, 9.6, 8.5, 9]}
        name  Age  CGP
0      Nisha   18  7.5
1  Rushikesh   20  9.6
2      Rahul   21  8.5
3      Banty   25  9.0
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'Age', 'CGP'], dtype='object')

In [24]:
df

        name  Age  CGP
0      Nisha   18  7.5
1  Rushikesh   20  9.6
2      Rahul   21  8.5
3      Banty   25  9.0

In [32]:
arr =  np.array([[1,2,3] , [4,5,6]])
df = pd.DataFrame(arr , columns = ["A" , "B" , "C"]  )

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [33]:
df = pd.read_csv("globalAirQuality.csv")

In [34]:
df

                        timestamp country  ... humidity  wind_speed
0      2025-11-04 18:25:17.554219      US  ...   70.168       3.725
1      2025-11-04 19:25:17.554219      US  ...   80.088       8.969
2      2025-11-04 20:25:17.554219      US  ...   62.783       9.650
3      2025-11-04 21:25:17.554219      US  ...   89.153       8.956
4      2025-11-04 22:25:17.554219      US  ...   76.499       4.017
...                           ...     ...  ...      ...         ...
17995  2025-11-19 13:25:17.554219      CH  ...   52.443       7.452
17996  2025-11-19 14:25:17.554219      CH  ...   85.678       4.496
17997  2025-11-19 15:25:17.554219      CH  ...   72.311       9.660
17998  2025-11-19 16:25:17.554219      CH  ...   31.880       2.642
17999  2025-11-19 17:25:17.554219      CH  ...   59.104       4.403

[18000 rows x 15 columns]

In [38]:

df.describe()

           latitude     longitude  ...      humidity    wind_speed
count  18000.000000  18000.000000  ...  18000.000000  18000.000000
mean      23.065980     37.655560  ...     57.714351      5.283910
std       26.156536     78.600701  ...     18.844908      2.741712
min      -37.814000   -123.121000  ...     25.002000      0.500000
25%       12.972000      2.352000  ...     41.320000      2.937000
50%       29.232000     42.146000  ...     57.847000      5.297000
75%       41.008000    103.820000  ...     74.234750      7.662000
max       60.170000    174.763000  ...     89.997000      9.999000

[8 rows x 12 columns]

In [73]:
#Selcting Data 
df
#columns 
df[["city" , "aqi"]]

#Rows 
df.loc[0:2]
df.iloc[0:2] # This is to indexing format 

#Row and Coloumns   cells
df.loc[ 0:2 , "city"] # first is [ row , col ]

0    New York
1    New York
2    New York
Name: city, dtype: object

In [74]:
#filtering Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30) ]
df[ (df["aqi"] > 100) & (df["temperature"] < 30) ]
aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ] [["city" , "aqi"]]
print(aqi_data)
aqi_data.iloc[100]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

city    Los Angeles
aqi             102
Name: 674, dtype: object

In [76]:
df.query("aqi > 100 & temperature > 30 ") [["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [122]:
#Create a file to practice the Panda 
df1 = pd.read_csv("store.csv") # TO input the file

In [123]:
df1

      name   age  marks        city
0    Rahul  22.0   85.0        Pune
1     Amit   NaN   78.0      Mumbai
2    Sneha  23.0   92.0      Nashik
3    Priya  22.0    NaN  Aurangabad
4    Rohan  24.0   67.0        Pune
5     Neha  21.0   74.0         NaN
6    Karan   NaN   81.0      Nagpur
7    Pooja  22.0   95.0      Nashik
8    Vikas  24.0    NaN        Pune
9   Anjali  21.0   83.0  Aurangabad
10   Sagar  23.0   76.0         NaN
11   Meena   NaN   88.0      Mumbai

In [135]:
# Methods of Data Frame 
df1.columns # To show columns 
df1.head()# To top 5 Show 
df1.tail()#  To last 5 Show 
df1.describe()# TO gate mean , mininum ,max , mean all show
df1.info()# show all inforamtion show

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    12 non-null     object
 1   age     9 non-null      float64
 2   marks   10 non-null     float64
 3   city    10 non-null     object
dtypes: float64(2), object(2)
memory usage: 516.0+ bytes

In [136]:
df1

      name   age  marks        city
0    Rahul  22.0   85.0        Pune
1     Amit   NaN   78.0      Mumbai
2    Sneha  23.0   92.0      Nashik
3    Priya  22.0    NaN  Aurangabad
4    Rohan  24.0   67.0        Pune
5     Neha  21.0   74.0         NaN
6    Karan   NaN   81.0      Nagpur
7    Pooja  22.0   95.0      Nashik
8    Vikas  24.0    NaN        Pune
9   Anjali  21.0   83.0  Aurangabad
10   Sagar  23.0   76.0         NaN
11   Meena   NaN   88.0      Mumbai

In [137]:
# Clear Data 
#handling Missing value